"""Textes des propositions 4 à 6 (toutes les pièces travaillent, aucune n'est posée à plat au sol)."""
import math
R = math.sqrt(2); L30 = R * math.sqrt(3)
from contenu import TANGRAM

MAQUETTES = {
 "miroir": {
  "titre": "Le Miroir", "principe": "Symétrie",
  "intro": "Tout est construit de part et d'autre d'un plan de symétrie est–ouest : deux ailes, deux poteaux. Sur ce plan se dressent les pièces qui sont elles-mêmes symétriques : la colonne et l'auvent. Sous la colonne, un passage ; à l'est un porche, à l'ouest un double cadrage sur le couchant.",
  "arguments": ["Climat : les deux ailes descendent à 30° vers le nord et le sud : la pluie s'écoule des deux côtés, et le vent glisse sur leur dos.",
                "Orientation : l'axe va d'est en ouest. Le porche reçoit le soleil du matin ; à l'ouest, la colonne coupe la vue en deux cadres, deux images du couchant.",
                "Géométrie : 4 à 5,3 cm de hauteur. Le personnage entre par le porche, longe l'aile nord, traverse la colonne sous le parallélogramme et ressort sous l'aile sud, face à l'ouest."],
  "etapes": [
   {"titre": "La colonne", "piece": "C", "texte": "Pose le carré rouge debout dans l'axe est–ouest, à l'extrémité ouest. Son côté haut est à 5,3 cm.",
    "logique": "Il est dans le plan de symétrie : il est lui-même symétrique. À l'ouest, il partage la vue en deux cadres.", "colle": [[(0, 0, 0), (R, 0, 0)]]},
   {"titre": "Le contrefort", "piece": "Pa", "texte": "Colle le parallélogramme bleu dans le prolongement du carré, debout, penché vers l'est : son petit côté haut continue le haut du carré.",
    "logique": "Le haut du carré et du parallélogramme forme un faîtage de 10,6 cm, de la longueur des petits côtés des grands triangles. Sous sa pente, il reste un passage.", "colle": [[(R, 0, R), (R, 0, 0)]]},
   {"titre": "L'aile nord", "piece": "G1", "texte": "Colle un petit côté du grand triangle orange sur le faîtage. L'aile descend à 30° vers le nord jusqu'au sol.",
    "logique": "Elle protège le côté nord du vent et de la pluie.", "colle": [[(0, 0, R), (2 * R, 0, R)]]},
   {"titre": "L'aile sud", "piece": "G2", "texte": "Colle le grand triangle turquoise de l'autre côté du même faîtage, à 30° vers le sud.",
    "logique": "Symétrie : c'est l'aile nord vue dans le miroir.", "colle": [[(0, 0, R), (2 * R, 0, R)]]},
   {"titre": "Le poteau nord du porche", "piece": "P1", "texte": "Pose le petit triangle bleu clair debout sur un petit côté, à l'est, au nord de l'axe. Son autre petit côté monte à 5,3 cm.",
    "logique": "Il portera un coin de l'auvent.", "colle": [[(2 * R, R, 0), (3 * R, R, 0)]]},
   {"titre": "Le poteau sud du porche", "piece": "P2", "texte": "Pose le petit triangle vert de la même façon, au sud de l'axe.",
    "logique": "Symétrie : c'est le poteau nord dans le miroir.", "colle": [[(2 * R, -R, 0), (3 * R, -R, 0)]]},
   {"titre": "L'auvent du porche", "piece": "M", "texte": "Pose le triangle moyen jaune à plat, à 5,3 cm : sa pointe au bout du faîtage, son grand côté sur les deux poteaux.",
    "logique": "Symétrique, il est posé sur l'axe. Il abrite l'entrée est, au soleil du matin.", "colle": [[(3 * R, R, R), (3 * R, -R, R)]]},
  ],
  "vues": {"perso": [(5.0, 0.6, 0.62), (0, 0.6, 0.6)], "ouest": [(-7.2, 0, 2.0), (2, 0, 0.8)]},
 },
 "tipi": {
  "titre": "Le Tipi des deux soleils", "principe": "Pliage",
  "intro": "Le carré des deux grands triangles, plié en toit le long de son grand côté. Au milieu, le triangle moyen remplit exactement la coupe du toit et le sépare en deux chambres : celle du matin, ouverte à l'est, et celle du soir, ouverte à l'ouest. Aux deux bouts, un auvent en porte-à-faux.",
  "arguments": ["Climat : deux pans à 45° qui descendent jusqu'au sol, au nord et au sud : la pluie, la neige et le vent glissent dessus.",
                "Orientation : la chambre ouest regarde le couchant, la chambre est le lever du soleil. Les côtés nord et sud restent ouverts en triangles : la lumière entre de biais.",
                "Géométrie : 5,3 cm sous le faîtage, 4 cm sur le chemin. Le personnage entre sous l'auvent ouest et s'arrête face au couchant, dos au triangle moyen."],
  "etapes": [
   {"titre": "Le poteau ouest", "piece": "P1", "texte": "Pose le petit triangle bleu clair debout sur un petit côté, dans l'axe est–ouest : son autre petit côté est un poteau vertical de 5,3 cm, son grand côté un contrefort vers l'ouest.",
    "logique": "Il portera le bout ouest du faîtage.", "colle": [[(0, 0, 0), (-R, 0, 0)]]},
   {"titre": "Le poteau est", "piece": "P2", "texte": "Pose le petit triangle vert de la même façon, 15 cm plus à l'est, contrefort vers l'est.",
    "logique": "Rotation : c'est le poteau ouest tourné d'un demi-tour.", "colle": [[(4, 0, 0), (4 + R, 0, 0)]]},
   {"titre": "Le pan nord", "piece": "G1", "texte": "Pose le grand côté du grand triangle orange en haut des deux poteaux. Sa pointe descend à 45° vers le nord jusqu'au sol.",
    "logique": "Première moitié du carré plié.", "colle": [[(0, 0, R), (4, 0, R)]]},
   {"titre": "Le pan sud", "piece": "G2", "texte": "Colle le grand triangle turquoise contre le pan nord, le long du même grand côté, à 45° vers le sud.",
    "logique": "Pliage : les deux grands triangles forment le carré plié à angle droit.", "colle": [[(0, 0, R), (4, 0, R)]]},
   {"titre": "La cloison", "piece": "M", "texte": "Glisse le triangle moyen jaune debout sous le milieu du faîtage, en travers : il remplit exactement le triangle du toit.",
    "logique": "Sa forme est exactement la coupe du toit plié : il le raidit et crée deux chambres dos à dos, celle du matin et celle du soir.", "colle": [[(2, -R, 0), (2, 0, R)], [(2, R, 0), (2, 0, R)]]},
   {"titre": "L'auvent du soir", "piece": "C", "texte": "Colle le carré rouge à plat, à 5,3 cm, au bout ouest du faîtage, en porte-à-faux vers l'ouest.",
    "logique": "Il abrite l'entrée ouest de la pluie et du soleil haut, et cadre le couchant par-dessous.", "colle": [[(0, -R / 2, R), (0, R / 2, R)]]},
   {"titre": "L'auvent du matin", "piece": "Pa", "texte": "Colle le parallélogramme bleu à plat au bout est du faîtage, en porte-à-faux, tourné vers le nord-est.",
    "logique": "Le pendant de l'auvent ouest, orienté vers le lever du soleil d'été.", "colle": [[(4, -R / 2, R), (4, R / 2, R)]]},
  ],
  "vues": {"perso": [(1.5, 0.35, 0.62), (-4, 0.35, 0.65)], "ouest": [(-7.5, -0.8, 2.0), (1.8, 0, 0.7)]},
 },
 "belvedere": {
  "titre": "Le Belvédère", "principe": "Rotation et promenade",
  "intro": "Deux murs-triangles en équerre, au nord et à l'est, l'un tourné d'un quart de tour par rapport à l'autre. L'auvent est posé d'une pointe à l'autre. Dessous, une plateforme à 3,75 cm, sur deux petits triangles croisés. Le personnage monte par la rampe et regarde le couchant, à l'abri.",
  "arguments": ["Climat : les deux murs ferment le nord et l'est contre le vent d'hiver et les tempêtes ; l'auvent protège la plateforme de la pluie et du soleil de midi.",
                "Orientation : la plateforme s'ouvre au sud-ouest et à l'ouest : on monte pour voir le couchant au-dessus des murs bas.",
                "Géométrie : la rampe monte de 3,75 cm ; sur la plateforme, il reste 3,75 cm sous l'auvent pour le personnage de 3 cm."],
  "etapes": [
   {"titre": "Le mur nord", "piece": "G1", "texte": "Pose le grand triangle orange debout sur son grand côté, au nord, dans l'axe est–ouest.",
    "logique": "Il arrête le vent froid du nord.", "colle": [[(0, 4, 0), (4, 4, 0)]]},
   {"titre": "Le mur est", "piece": "G2", "texte": "Pose le grand triangle turquoise de la même façon à l'est, en équerre : les deux murs se touchent par un coin.",
    "logique": "Rotation : c'est le mur nord tourné d'un quart de tour. Les deux pointes sont à 7,5 cm, à 10,6 cm l'une de l'autre.", "colle": [[(4, 0, 0), (4, 4, 0)]]},
   {"titre": "L'auvent", "piece": "M", "texte": "Pose le grand côté du triangle moyen jaune d'une pointe à l'autre, à 7,5 cm. Sa pointe avance vers le sud-ouest.",
    "logique": "Son grand côté mesure exactement la distance entre les deux pointes : il relie les deux murs et couvre la plateforme.", "colle": [[(2, 4, 2), (4, 2, 2)]]},
   {"titre": "Le pied sud", "piece": "P1", "texte": "Pose le petit triangle bleu clair debout sur son grand côté, sous l'auvent, dans l'axe est–ouest. Sa pointe est à 3,75 cm.",
    "logique": "Il portera la plateforme.", "colle": [[(1.707, 2, 0), (3.707, 2, 0)]]},
   {"titre": "Le pied ouest", "piece": "P2", "texte": "Pose le petit triangle vert de la même façon, en travers du premier.",
    "logique": "Rotation : c'est le premier pied tourné d'un quart de tour. Les deux pieds se croisent à angle droit, comme les deux murs.", "colle": [[(2, 1.707, 0), (2, 3.707, 0)]]},
   {"titre": "La plateforme", "piece": "C", "texte": "Pose le carré rouge à plat sur les deux pointes, à 3,75 cm.",
    "logique": "Le belvédère : on y est à l'abri sous l'auvent, au-dessus des murs bas, face au couchant.", "colle": [[(2.707, 2, 0.85), (2.707, 2, 1)], [(2, 2.707, 0.85), (2, 2.707, 1)]]},
   {"titre": "La rampe", "piece": "Pa", "texte": "Colle un petit côté du parallélogramme bleu sous le bord ouest de la plateforme. L'autre petit côté repose sur le sol, au sud-ouest.",
    "logique": "La promenade : on monte en tournant vers la vue.", "colle": [[(2, 2, 1), (2, 2 + R, 1)]]},
  ],
  "vues": {"perso": [(3.0, 3.0, 1.62), (-4, 1.2, 1.2)], "ouest": [(-6.0, -3.5, 2.6), (2.2, 2.2, 0.8)]},
 },
}
