"""Textes des variantes 7 à 9, dans l'esprit du Miroir."""
import math
R = math.sqrt(2); G = R / 2; L30 = R * math.sqrt(3)

MAQUETTES = {
 "fente": {
  "titre": "La Fente", "principe": "Symétrie",
  "intro": "Deux demi-toits symétriques, inclinés à 30° vers le nord et le sud, laissent entre eux une fente de 5,3 cm : un puits de lumière au-dessus du passage. À l'ouest, un linteau relie les deux toits et encadre le couchant ; à l'est, un porche sur deux poteaux.",
  "arguments": ["Climat : les toits descendent vers l'extérieur, la pluie part au nord et au sud. Seule la pluie qui tombe dans la fente entre, comme dans un patio.",
                "Orientation : la fente suit l'axe est–ouest. Le porche est accueille le soleil du matin ; à l'ouest, sous le linteau, une fenêtre cadre le couchant.",
                "Géométrie : 5,3 cm de haut partout sur le chemin. Le personnage entre par le porche, passe sous la fente, en pleine lumière, et s'arrête sous le linteau, face au couchant."],
  "etapes": [
   {"titre": "Le pilier ouest", "piece": "Pa", "texte": "Pose le parallélogramme bleu debout dans l'axe est–ouest, penché vers l'ouest. Son petit côté haut est à 5,3 cm.",
    "logique": "Il est dans le plan de symétrie. Vu depuis l'ouest, ce n'est qu'un trait : il ne gêne pas la vue.", "colle": [[(0, 0, 0), (-R, 0, 0)]]},
   {"titre": "Le linteau", "piece": "C", "texte": "Pose le carré rouge à plat sur le pilier, à 5,3 cm, en travers de l'axe.",
    "logique": "Ses deux côtés est–ouest seront les départs des deux toits. Dessous, la fenêtre ouest.", "colle": [[(0, 0, R), (R, 0, R)]]},
   {"titre": "Le poteau nord", "piece": "P1", "texte": "Pose le petit triangle bleu clair debout sur un petit côté, 10,6 cm plus à l'est, au nord de l'axe. Son contrefort part vers l'est.",
    "logique": "Il porte le bout est du toit nord.", "colle": [[(2 * R, G, 0), (3 * R, G, 0)]]},
   {"titre": "Le poteau sud", "piece": "P2", "texte": "Pose le petit triangle vert de la même façon, au sud de l'axe.",
    "logique": "Symétrie : c'est le poteau nord dans le miroir. Entre les deux, 5,3 cm : la largeur de la fente.", "colle": [[(2 * R, -G, 0), (3 * R, -G, 0)]]},
   {"titre": "Le toit nord", "piece": "G1", "texte": "Pose un petit côté du grand triangle orange sur le bord nord du linteau et sur le poteau nord. Le toit descend à 30° vers le nord jusqu'au sol.",
    "logique": "Il protège du vent du nord et rejette la pluie vers l'extérieur.", "colle": [[(0, G, R), (2 * R, G, R)]]},
   {"titre": "Le toit sud", "piece": "G2", "texte": "Pose le grand triangle turquoise de la même façon, au sud.",
    "logique": "Symétrie : c'est le toit nord dans le miroir. Entre les deux faîtages, la fente reste ouverte sur le ciel.", "colle": [[(0, -G, R), (2 * R, -G, R)]]},
   {"titre": "L'auvent du matin", "piece": "M", "texte": "Pose le triangle moyen jaune à plat sur les deux poteaux, à 5,3 cm, pointe vers l'est.",
    "logique": "Symétrique, il est posé sur l'axe. Il abrite l'entrée, au soleil du matin.", "colle": [[(2 * R, -R, R), (2 * R, R, R)]]},
  ],
  "vues": {"perso": [(4.4, 0, 0.62), (-3, 0, 0.6)], "ouest": [(-7.0, -0.6, 1.9), (1.8, 0, 0.8)]},
 },
 "oiseau": {
  "titre": "L'Oiseau", "principe": "Symétrie",
  "intro": "La colonne du Miroir, mais les deux ailes se relèvent à 30° : l'abri s'ouvre vers le ciel et la lumière. La tête, le triangle moyen, pointe vers le couchant ; la queue, deux petits triangles en miroir, vers le levant.",
  "arguments": ["Climat : la pluie glisse des deux ailes vers le pli, puis vers la tête et la queue qui la rejettent loin du passage, comme des gargouilles.",
                "Orientation : l'axe est–ouest relie le levant et le couchant. Les ailes relevées laissent entrer la lumière du nord et du sud, et protègent du soleil de midi.",
                "Géométrie : au moins 5,3 cm sous les ailes, 10,6 cm à leurs pointes. Le personnage longe la colonne, sous l'aile nord, de la queue jusqu'à la tête."],
  "etapes": [
   {"titre": "La colonne", "piece": "C", "texte": "Pose le carré rouge debout dans l'axe est–ouest. Son côté haut est à 5,3 cm.",
    "logique": "Il est dans le plan de symétrie, comme dans le Miroir.", "colle": [[(0, 0, 0), (R, 0, 0)]]},
   {"titre": "Le contrefort", "piece": "Pa", "texte": "Colle le parallélogramme bleu dans le prolongement du carré, penché vers l'est. Leurs deux côtés hauts forment un pli de 10,6 cm.",
    "logique": "Le pli a la longueur des petits côtés des grands triangles.", "colle": [[(R, 0, R), (R, 0, 0)]]},
   {"titre": "L'aile nord", "piece": "G1", "texte": "Colle un petit côté du grand triangle orange sur le pli. L'aile se relève de 30° vers le nord.",
    "logique": "Relevée, elle ouvre l'abri au ciel et fait couler la pluie vers le pli.", "colle": [[(0, 0, R), (2 * R, 0, R)]]},
   {"titre": "L'aile sud", "piece": "G2", "texte": "Colle le grand triangle turquoise sur le même pli, relevé de 30° vers le sud.",
    "logique": "Symétrie : c'est l'aile nord dans le miroir.", "colle": [[(0, 0, R), (2 * R, 0, R)]]},
   {"titre": "La queue (1)", "piece": "P1", "texte": "Colle le petit triangle bleu clair à plat au bout est du pli, à 5,3 cm, côté nord.",
    "logique": "Il recueille l'eau du pli et la rejette à l'est.", "colle": [[(2 * R, 0, R), (3 * R, 0, R)]]},
   {"titre": "La queue (2)", "piece": "P2", "texte": "Colle le petit triangle vert contre le premier, côté sud.",
    "logique": "Symétrie : c'est le premier petit triangle dans le miroir. À eux deux, ils forment la queue.", "colle": [[(2 * R, 0, R), (3 * R, 0, R)]]},
   {"titre": "La tête", "piece": "M", "texte": "Colle le triangle moyen jaune à plat au bout ouest du pli, à 5,3 cm, pointe vers l'ouest.",
    "logique": "Symétrique, sur l'axe : il pointe vers le couchant et abrite la sortie ouest.", "colle": [[(0, -R, R), (0, R, R)]]},
  ],
  "vues": {"perso": [(4.4, 0.5, 0.62), (-3, 0.5, 0.75)], "ouest": [(-7.0, -0.8, 2.0), (1.6, 0, 1.0)]},
 },
 "tourne": {
  "titre": "Le Miroir tourné", "principe": "Rotation",
  "intro": "La colonne et les ailes du Miroir, mais l'aile sud est l'aile nord tournée d'un demi-tour : le toit se tord. Au nord-ouest et au sud-est, les ailes ferment ; au nord-est et au sud-ouest, elles s'ouvrent. À l'ouest, un porche sur deux poteaux regarde le couchant.",
  "arguments": ["Climat : les ailes à 30° rejettent la pluie ; l'aile nord, haute à l'ouest, arrête le vent du nord-ouest, l'aile sud, haute à l'est, coupe le soleil chaud du matin d'été.",
                "Orientation : les ouvertures alternent : au nord-est pour la lumière douce, au sud-ouest pour le couchant d'hiver, et le porche ouest pour le couchant d'été.",
                "Géométrie : au moins 3,6 cm sur le chemin. Le personnage entre par le nord-est, traverse la colonne sous le parallélogramme et sort par le porche ouest."],
  "etapes": [
   {"titre": "La colonne", "piece": "C", "texte": "Pose le carré rouge debout dans l'axe est–ouest. Son côté haut est à 5,3 cm.",
    "logique": "Le centre de la composition, comme dans le Miroir.", "colle": [[(0, 0, 0), (R, 0, 0)]]},
   {"titre": "Le contrefort", "piece": "Pa", "texte": "Colle le parallélogramme bleu dans le prolongement du carré, penché vers l'est. Dessous, il reste un passage.",
    "logique": "Le pli fait 10,6 cm, la longueur des petits côtés des grands triangles.", "colle": [[(R, 0, R), (R, 0, 0)]]},
   {"titre": "L'aile nord", "piece": "G1", "texte": "Colle un petit côté du grand triangle orange sur le pli, l'angle droit à l'ouest. L'aile descend à 30° vers le nord.",
    "logique": "Haute à l'ouest, elle arrête le vent du nord-ouest.", "colle": [[(0, 0, R), (2 * R, 0, R)]]},
   {"titre": "L'aile sud", "piece": "G2", "texte": "Colle le grand triangle turquoise sur le même pli, l'angle droit à l'est, à 30° vers le sud.",
    "logique": "Rotation : c'est l'aile nord tournée d'un demi-tour autour du centre du pli.", "colle": [[(0, 0, R), (2 * R, 0, R)]]},
   {"titre": "Le poteau nord", "piece": "P1", "texte": "Pose le petit triangle bleu clair debout sur un petit côté, à l'ouest de la colonne, au nord de l'axe.",
    "logique": "Il porte un coin de l'auvent du couchant.", "colle": [[(-R, R, 0), (0, R, 0)]]},
   {"titre": "Le poteau sud", "piece": "P2", "texte": "Pose le petit triangle vert de la même façon, au sud de l'axe.",
    "logique": "Symétrie : c'est le poteau nord dans le miroir.", "colle": [[(-R, -R, 0), (0, -R, 0)]]},
   {"titre": "L'auvent du couchant", "piece": "M", "texte": "Pose le triangle moyen jaune à plat, à 5,3 cm : sa pointe au bout ouest du pli, son grand côté sur les deux poteaux.",
    "logique": "Le porche ouest : on s'y arrête, à l'abri, face au couchant.", "colle": [[(-R, R, R), (-R, -R, R)]]},
  ],
  "vues": {"perso": [(4.4, 0.8, 0.62), (-3, 0.2, 0.6)], "ouest": [(-7.2, 0.6, 2.0), (2, 0, 0.8)]},
 },
}
